server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: servidor_gateway
  cloud:
    gateway:
      default-filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"       
      routes:
        - id: serv-productos        
              #lb:// cuando se va a accede  r a traves de Eureka
          uri: lb://servicio-productos1 #http://localhost:8080
          predicates:
            - Path=/sproductos/**
          filters:
            - RewritePath=/sproductos/*, /